### PR TITLE
Pixelbuf Support #2

### PR DESCRIPTION
**Pull request by dunkmann00**
This adds support for CP _pixelbuf. This aims to complete PR #74.

Works in CP versions 5 and 4 (fallback to pure python Pixelbuf impl.). In order to support the pure python version, [PR #18](https://github.com/adafruit/Adafruit_CircuitPython_Pypixelbuf/pull/18) from the [Adafruit_CircuitPython_Pypixelbuf](https://github.com/adafruit/Adafruit_CircuitPython_Pypixelbuf) repo is also necessary for this to work.

### CODE REVIEW

**Comment by dunkmann00** [comment]
The failed test is addressed in [Adafruit_CircuitPython_Pypixelbuf #18](https://github.com/adafruit/Adafruit_CircuitPython_Pypixelbuf/pull/18)

**Comment by tannewt** [comment]
PixelBuf updates are merged but cannot be released until https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel_SPI/issues/14 is resolved and therefore block this PR from being released.

**Comment by tannewt** [comment]
Ok, PyPixelBuf 2.0.0 and NeoPixel_SPI 0.8.0 have been released. I'm going to merge this now and merge once I confirm the other two are on pypi.

**Comment by ladyada** [comment]
awesome!!

**Pull request merged**
